import 'package:axiom/src/core/domain/entities/base/audited_entity.dart';
import 'package:axiom/src/core/domain/mixins/archivable.dart';
import 'package:axiom/src/core/domain/mixins/deletable.dart';
import 'package:axiom/src/core/domain/value_objects/calendar_date.dart';
import 'package:axiom/src/core/identity/ids/transaction_series_id.dart';
import 'package:axiom/src/core/ports/clock/clock.dart';
import 'package:axiom/src/core/ports/clock/clock_factory.dart';
import 'package:axiom/src/features/assets/domain/value_objects/asset_amount.dart';
import 'package:axiom/src/features/transactions/domain/enums/ledger_entry_role.dart';
import 'package:axiom/src/features/transactions/domain/enums/transaction_kind.dart';
import 'package:axiom/src/features/transactions/domain/value_objects/recurrence_amount_end.dart';
import 'package:axiom/src/features/transactions/domain/value_objects/recurrence_exception.dart';
import 'package:axiom/src/features/transactions/domain/value_objects/recurrence_rule.dart';
import 'package:axiom/src/features/transactions/domain/value_objects/transaction_template.dart';
import 'package:dart_mappable/dart_mappable.dart';
import 'package:decimal/decimal.dart';

part 'transaction_series.mapper.dart';

/// Defines a recurring transaction specification.
///
/// A transaction series owns:
///
/// - [template], describing the normal transaction shape;
/// - [recurrenceRule], describing the normal calendar recurrence; and
/// - [exceptions], describing one-off deviations from that recurrence.
///
/// Generated occurrences remain ordinary transactions and do not contain this
/// entity's [TransactionSeriesId].
///
/// ## Amount-based termination
///
/// [recurrenceRule] may define a cumulative monetary termination target.
///
/// Amount termination currently supports expense and income series only,
/// because each has exactly one meaningful primary transaction amount.
///
/// The configured target must use the same asset and direction as the primary
/// transaction amount of [template].
///
/// A recurrence exception that supplies a replacement template must preserve
/// that same amount asset and direction.
///
/// The normal series template must have a positive primary amount so an
/// amount-only recurrence can make progress.
///
/// A replacement template may contain a zero primary amount; that particular
/// occurrence simply contributes no progress toward the target.
///
/// ## Exact final occurrence
///
/// An exact-target amount rule may reduce the primary amount of the final
/// occurrence.
///
/// This entity does not modify ledger entries, account amounts, valuation
/// amounts, or allocation splits itself.
///
/// Rebuilding a financially valid transaction for a reduced final amount
/// belongs to the occurrence-generation application workflow because that
/// workflow has access to asset metadata, exchange rates, valuation settings,
/// and allocation calculation rules.
///
/// ## Recurrence exceptions
///
/// Every exception is keyed by the original scheduled date produced by
/// [recurrenceRule].
///
/// At most one exception may exist for each scheduled occurrence date.
///
/// A replacement date does not itself become part of the base recurrence rule.
///
/// ## Archival
///
/// Archiving disables the series for normal future occurrence generation while
/// preserving the series and its historical recurrence definition.
///
/// ## Deletion
///
/// Deletion disables future generation and represents removal of the series
/// itself.
///
/// Neither archival nor deletion modifies transactions that have already been
/// generated.
///
/// ## Invariants
///
/// - every exception refers to a date generated by [recurrenceRule];
/// - no two exceptions refer to the same scheduled occurrence date;
/// - [exceptions] is immutable;
/// - amount termination is supported only for expense and income series;
/// - an amount target must match the primary transaction amount's asset and
///   direction;
/// - the normal template primary amount must be known and greater than zero
///   when amount termination is configured;
/// - replacement templates participating in amount termination must expose one
///   known compatible primary amount;
/// - [archivedAt], when present, cannot precede [createdAt];
/// - [archivedAt], when present, cannot follow [modifiedAt];
/// - [deletedAt], when present, cannot precede [createdAt];
/// - when both are present, [deletedAt] cannot precede [archivedAt];
/// - inherited audit and entity-version invariants remain valid.
@MappableClass()
final class TransactionSeries extends AuditedEntity<TransactionSeriesId>
    with Archivable, Deletable, TransactionSeriesMappable {
  /// Reusable default transaction specification.
  final TransactionTemplate template;

  /// Calendar and termination rule defining the recurrence.
  final RecurrenceRule recurrenceRule;

  /// One-off exceptions to scheduled recurrence slots.
  final List<RecurrenceException> exceptions;

  /// {@macro archivable.archived_at}
  @override
  final DateTime? archivedAt;

  /// {@macro deletable.deleted_at}
  @override
  final DateTime? deletedAt;

  /// Creates a persisted or rehydrated transaction-series snapshot.
  ///
  /// [exceptions] is defensively copied and exposed as an immutable
  /// collection.
  ///
  /// Throws an [ArgumentError] when recurrence, amount-target, exception, or
  /// lifecycle invariants are violated.
  @MappableConstructor()
  TransactionSeries({
    required super.id,
    required this.template,
    required this.recurrenceRule,
    List<RecurrenceException> exceptions = const [],
    this.archivedAt,
    this.deletedAt,
    required super.createdAt,
    required super.modifiedAt,
    required super.entityVersion,
  }) : exceptions = List.unmodifiable(exceptions) {
    _validateExceptions();
    _validateAmountTermination();
    _validateLifecycle();
  }

  /// Creates a new active transaction series.
  ///
  /// Generates a [TransactionSeriesId], initializes entity version `1`, and
  /// uses the same clock instant for creation and modification metadata.
  factory TransactionSeries.create({
    required TransactionTemplate template,
    required RecurrenceRule recurrenceRule,
    List<RecurrenceException> exceptions = const [],
    Clock? clock,
  }) {
    final resolvedClock = clock ?? createClock();
    final now = resolvedClock.nowUtc;

    return TransactionSeries(
      id: TransactionSeriesId.generate(),
      template: template,
      recurrenceRule: recurrenceRule,
      exceptions: exceptions,
      createdAt: now,
      modifiedAt: now,
      entityVersion: 1,
    );
  }

  /// Whether this series may participate in normal future generation.
  bool get isGenerationEnabled => !isArchived && !isDeleted;

  /// Monetary termination rule configured for this series, when any.
  RecurrenceAmountEnd? get amountEnd => recurrenceRule.end?.amount;

  /// Number of recurrence slots added because skipped occurrences explicitly
  /// requested compensation at the end of the series.
  int get additionalOccurrenceCount {
    return exceptions
        .where((exception) => exception.isSkipped && exception.extendsSeries)
        .length;
  }

  /// Returns the scheduled recurrence date at [index], including any recurrence
  /// extension caused by compensating skipped occurrences.
  CalendarDate? scheduledOccurrenceAt(int index) {
    return recurrenceRule.occurrenceAt(
      index,
      additionalOccurrences: additionalOccurrenceCount,
    );
  }

  /// Whether the series schedules an occurrence on [date].
  ///
  /// Compensating extension slots are included.
  bool definesOccurrenceOn(CalendarDate date) {
    return recurrenceRule.occursOn(
      date,
      additionalOccurrences: additionalOccurrenceCount,
    );
  }

  /// Returns the exception attached to the original scheduled date.
  RecurrenceException? exceptionFor(CalendarDate scheduledOn) {
    for (final exception in exceptions) {
      if (exception.scheduledOn.compareTo(scheduledOn) == 0) {
        return exception;
      }
    }

    return null;
  }

  /// Resolves the date and transaction template for recurrence [index].
  ///
  /// Returns `null` when:
  ///
  /// - the calendar/count recurrence has ended; or
  /// - a skip exception suppresses this recurrence slot.
  ///
  /// Amount termination is not evaluated because it requires cumulative
  /// financial progress.
  ///
  /// Lifecycle state is also deliberately ignored. Callers generating future
  /// transactions must additionally check [isGenerationEnabled].
  ({CalendarDate date, TransactionTemplate template})? resolveOccurrenceAt(
    int index,
  ) {
    final scheduledOn = scheduledOccurrenceAt(index);

    if (scheduledOn == null) {
      return null;
    }

    final exception = exceptionFor(scheduledOn);

    if (exception == null) {
      return (date: scheduledOn, template: template);
    }

    final effectiveDate = exception.effectiveDate;
    final effectiveTemplate = exception.resolveTemplate(template);

    if (effectiveDate == null || effectiveTemplate == null) {
      return null;
    }

    return (date: effectiveDate, template: effectiveTemplate);
  }

  /// Returns the primary transaction amount used for amount-target progress by
  /// [occurrenceTemplate].
  ///
  /// This helper is meaningful only when [amountEnd] is configured.
  ///
  /// Series construction guarantees that the default and exception
  /// replacement templates have exactly one compatible known primary amount.
  ///
  /// Throws a [StateError] when this series has no amount target.
  AssetAmount amountProgressFor(TransactionTemplate occurrenceTemplate) {
    final configuredAmountEnd = amountEnd;

    if (configuredAmountEnd == null) {
      throw StateError(
        'Transaction series does not define an amount-based recurrence end.',
      );
    }

    return _compatiblePrimaryAmount(
      occurrenceTemplate,
      configuredAmountEnd,
      requirePositive: false,
    );
  }

  /// Resolves the primary amount that should be generated next.
  ///
  /// [accumulatedAmount] is cumulative progress from previous resolved
  /// recurrence occurrences.
  ///
  /// [occurrenceTemplate] must be the template already resolved after applying
  /// any exception for the next recurrence slot.
  ///
  /// Returns `null` when the cumulative target has already been reached.
  ///
  /// For an exact-target recurrence the returned amount may be smaller than the
  /// occurrence template's normal primary amount.
  ///
  /// Throws a [StateError] when this series does not define amount-based
  /// termination.
  AssetAmount? resolveNextAmount({
    required AssetAmount accumulatedAmount,
    required TransactionTemplate occurrenceTemplate,
  }) {
    final configuredAmountEnd = amountEnd;

    if (configuredAmountEnd == null) {
      throw StateError(
        'Transaction series does not define an amount-based recurrence end.',
      );
    }

    final normalAmount = amountProgressFor(occurrenceTemplate);

    return configuredAmountEnd.resolveNextAmount(
      accumulatedAmount: accumulatedAmount,
      normalOccurrenceAmount: normalAmount,
    );
  }

  void _validateExceptions() {
    final scheduledDates = <String>{};
    final extensionCount = exceptions
        .where((exception) => exception.isSkipped && exception.extendsSeries)
        .length;

    for (final exception in exceptions) {
      if (!recurrenceRule.occursOn(
        exception.scheduledOn,
        additionalOccurrences: extensionCount,
      )) {
        throw ArgumentError.value(
          exception,
          'exceptions',
          'Every recurrence exception must refer to a date generated by the '
              'series recurrence rule.',
        );
      }

      final dateKey = exception.scheduledOn.toString();

      if (!scheduledDates.add(dateKey)) {
        throw ArgumentError.value(
          exception,
          'exceptions',
          'Only one recurrence exception may exist for each scheduled '
              'occurrence date.',
        );
      }
    }
  }

  void _validateAmountTermination() {
    final configuredAmountEnd = amountEnd;

    if (configuredAmountEnd == null) {
      return;
    }

    if (template.kind != TransactionKind.expense &&
        template.kind != TransactionKind.income) {
      throw ArgumentError.value(
        configuredAmountEnd,
        'recurrenceRule',
        'Amount-based recurrence termination is supported only for expense '
            'and income transaction series.',
      );
    }

    _compatiblePrimaryAmount(
      template,
      configuredAmountEnd,
      requirePositive: true,
    );

    for (final exception in exceptions) {
      final replacementTemplate = exception.replacementTemplate;

      if (replacementTemplate == null) {
        continue;
      }

      if (replacementTemplate.kind != template.kind) {
        throw ArgumentError.value(
          exception,
          'exceptions',
          'An amount-target recurrence replacement template must preserve the '
              'series transaction kind.',
        );
      }

      _compatiblePrimaryAmount(
        replacementTemplate,
        configuredAmountEnd,
        requirePositive: false,
      );
    }
  }

  AssetAmount _compatiblePrimaryAmount(
    TransactionTemplate candidate,
    RecurrenceAmountEnd configuredAmountEnd, {
    required bool requirePositive,
  }) {
    final primaryEntries = candidate.ledgerEntries
        .where((entry) => entry.role == LedgerEntryRole.primary)
        .toList(growable: false);

    if (primaryEntries.length != 1) {
      throw ArgumentError.value(
        candidate,
        'template',
        'An amount-target recurrence requires exactly one primary ledger '
            'entry.',
      );
    }

    final primaryAmount = primaryEntries.single.transactionAmount;

    if (primaryAmount.isUnknownAmount) {
      throw ArgumentError.value(
        candidate,
        'template',
        'An amount-target recurrence requires a known primary transaction '
            'amount.',
      );
    }

    if (requirePositive && primaryAmount.amount <= Decimal.zero) {
      throw ArgumentError.value(
        candidate,
        'template',
        'The normal transaction template of an amount-target recurrence must '
            'have a primary amount greater than zero.',
      );
    }

    if (primaryAmount.assetId != configuredAmountEnd.targetAmount.assetId) {
      throw ArgumentError.value(
        candidate,
        'template',
        'The primary transaction amount must use the recurrence target asset.',
      );
    }

    if (primaryAmount.direction != configuredAmountEnd.targetAmount.direction) {
      throw ArgumentError.value(
        candidate,
        'template',
        'The primary transaction amount must use the recurrence target '
            'direction.',
      );
    }

    return primaryAmount;
  }

  void _validateLifecycle() {
    if (archivedAt?.isBefore(createdAt) ?? false) {
      throw ArgumentError.value(
        archivedAt,
        'archivedAt',
        'Archive time cannot precede creation time.',
      );
    }

    if (archivedAt?.isAfter(modifiedAt) ?? false) {
      throw ArgumentError.value(
        archivedAt,
        'archivedAt',
        'Archive time cannot follow modification time.',
      );
    }

    if (deletedAt?.isBefore(createdAt) ?? false) {
      throw ArgumentError.value(
        deletedAt,
        'deletedAt',
        'Deletion time cannot precede creation time.',
      );
    }

    if (archivedAt != null &&
        deletedAt != null &&
        deletedAt!.isBefore(archivedAt!)) {
      throw ArgumentError.value(
        deletedAt,
        'deletedAt',
        'Deletion time cannot precede archive time.',
      );
    }
  }
}
