import 'package:axiom/src/core/domain/value_objects/calendar_date.dart';
import 'package:axiom/src/features/transactions/domain/enums/recurrence_exception_kind.dart';
import 'package:axiom/src/features/transactions/domain/value_objects/transaction_template.dart';
import 'package:dart_mappable/dart_mappable.dart';

part 'recurrence_exception.mapper.dart';

/// Defines a one-off exception to a recurring transaction series.
///
/// [scheduledOn] always identifies the original recurrence slot.
///
/// A skip may optionally [extendSeries]. When enabled, the skipped slot still
/// produces no transaction, but finite date/count recurrence boundaries are
/// extended by one recurrence slot.
@MappableClass()
final class RecurrenceException with RecurrenceExceptionMappable {
  /// Original date generated by the owning recurrence rule.
  final CalendarDate scheduledOn;

  /// Behavior applied to the scheduled occurrence.
  final RecurrenceExceptionKind kind;

  /// Replacement occurrence date.
  final CalendarDate? replacementOn;

  /// Replacement transaction template.
  final TransactionTemplate? replacementTemplate;

  /// Whether this skipped occurrence extends a finite series by one slot.
  ///
  /// This may only be `true` for [RecurrenceExceptionKind.skip].
  final bool extendsSeries;

  /// Creates a recurrence exception snapshot.
  @MappableConstructor()
  RecurrenceException({
    required this.scheduledOn,
    required this.kind,
    this.replacementOn,
    this.replacementTemplate,
    this.extendsSeries = false,
  }) {
    switch (kind) {
      case RecurrenceExceptionKind.skip:
        if (replacementOn != null) {
          throw ArgumentError.value(
            replacementOn,
            'replacementOn',
            'A skipped recurrence occurrence cannot have a replacement date.',
          );
        }

        if (replacementTemplate != null) {
          throw ArgumentError.value(
            replacementTemplate,
            'replacementTemplate',
            'A skipped recurrence occurrence cannot have a replacement '
                'template.',
          );
        }

      case RecurrenceExceptionKind.replacement:
        if (extendsSeries) {
          throw ArgumentError.value(
            extendsSeries,
            'extendsSeries',
            'A replacement recurrence exception cannot extend the series.',
          );
        }

        final changesDate =
            replacementOn != null && replacementOn!.compareTo(scheduledOn) != 0;

        if (!changesDate && replacementTemplate == null) {
          throw ArgumentError.value(
            kind,
            'kind',
            'A replacement recurrence exception must change its date, '
                'transaction template, or both.',
          );
        }
    }
  }

  /// Creates an exception suppressing one scheduled occurrence.
  ///
  /// When [extendsSeries] is `true`, a finite recurrence is extended by one
  /// recurrence slot to compensate for this skipped occurrence.
  factory RecurrenceException.skip({
    required CalendarDate scheduledOn,
    bool extendsSeries = false,
  }) {
    return RecurrenceException(
      scheduledOn: scheduledOn,
      kind: RecurrenceExceptionKind.skip,
      extendsSeries: extendsSeries,
    );
  }

  /// Creates an exception replacing one scheduled occurrence.
  factory RecurrenceException.replace({
    required CalendarDate scheduledOn,
    CalendarDate? replacementOn,
    TransactionTemplate? replacementTemplate,
  }) {
    return RecurrenceException(
      scheduledOn: scheduledOn,
      kind: RecurrenceExceptionKind.replacement,
      replacementOn: replacementOn,
      replacementTemplate: replacementTemplate,
    );
  }

  /// Whether this exception suppresses its scheduled occurrence.
  bool get isSkipped => kind == RecurrenceExceptionKind.skip;

  /// Whether this exception replaces its scheduled occurrence.
  bool get isReplacement => kind == RecurrenceExceptionKind.replacement;

  /// Effective occurrence date after applying this exception.
  CalendarDate? get effectiveDate {
    return switch (kind) {
      RecurrenceExceptionKind.skip => null,
      RecurrenceExceptionKind.replacement => replacementOn ?? scheduledOn,
    };
  }

  /// Resolves the transaction template to use for this exception.
  TransactionTemplate? resolveTemplate(TransactionTemplate seriesTemplate) {
    return switch (kind) {
      RecurrenceExceptionKind.skip => null,
      RecurrenceExceptionKind.replacement =>
        replacementTemplate ?? seriesTemplate,
    };
  }
}
