import 'package:axiom/src/core/domain/value_objects/calendar_date.dart';
import 'package:axiom/src/features/transactions/domain/enums/recurrence_exception_kind.dart';
import 'package:axiom/src/features/transactions/domain/value_objects/transaction_template.dart';
import 'package:dart_mappable/dart_mappable.dart';

part 'recurrence_exception.mapper.dart';

/// Defines a one-off exception to a recurring transaction series.
///
/// Exceptions are attached to the recurrence definition rather than generated
/// transactions.
///
/// [scheduledOn] identifies the original occurrence produced by the owning
/// recurrence rule. It never changes even when the occurrence is moved to
/// [replacementOn].
///
/// ## Skip semantics
///
/// A [RecurrenceExceptionKind.skip] exception suppresses the scheduled
/// occurrence entirely.
///
/// Skip exceptions cannot specify [replacementOn] or [replacementTemplate].
///
/// ## Replacement semantics
///
/// A [RecurrenceExceptionKind.replacement] exception replaces the scheduled
/// occurrence.
///
/// A replacement can:
///
/// - move the occurrence to another calendar date;
/// - replace the normal transaction template;
/// - or do both.
///
/// At least one effective change is required.
///
/// The replacement date is deliberately allowed to fall outside the ordinary
/// recurrence rule or its end boundary. For example, a final monthly payment
/// scheduled for September 30 may explicitly be moved to October 1.
///
/// ## Generated transactions
///
/// This value object does not contain a `TransactionId` and does not represent
/// a generated transaction.
///
/// An occurrence-generation workflow resolves this exception first, then
/// materializes the resulting template as an ordinary transaction.
///
/// ## Invariants
///
/// - skip exceptions cannot contain replacement values;
/// - replacement exceptions must change the date, template, or both;
/// - [scheduledOn] always remains the identity of the recurrence slot being
///   overridden.
///
/// Validation that [scheduledOn] actually belongs to the recurrence rule is
/// owned by `TransactionSeries`, because this value object does not have access
/// to that rule.
@MappableClass()
final class RecurrenceException with RecurrenceExceptionMappable {
  /// Original date generated by the owning recurrence rule.
  final CalendarDate scheduledOn;

  /// Behavior applied to the scheduled occurrence.
  final RecurrenceExceptionKind kind;

  /// Replacement occurrence date.
  ///
  /// `null` means a replacement remains on [scheduledOn].
  ///
  /// Must be `null` for skip exceptions.
  final CalendarDate? replacementOn;

  /// One-off transaction template replacing the series template.
  ///
  /// `null` means a replacement continues using the series's normal template.
  ///
  /// Must be `null` for skip exceptions.
  final TransactionTemplate? replacementTemplate;

  /// Creates a recurrence exception snapshot.
  ///
  /// Prefer [RecurrenceException.skip] and [RecurrenceException.replace] when
  /// creating new domain values.
  ///
  /// Throws an [ArgumentError] when the configured values are inconsistent
  /// with [kind].
  @MappableConstructor()
  RecurrenceException({
    required this.scheduledOn,
    required this.kind,
    this.replacementOn,
    this.replacementTemplate,
  }) {
    switch (kind) {
      case RecurrenceExceptionKind.skip:
        if (replacementOn != null) {
          throw ArgumentError.value(
            replacementOn,
            'replacementOn',
            'A skipped recurrence occurrence cannot have a replacement date.',
          );
        }

        if (replacementTemplate != null) {
          throw ArgumentError.value(
            replacementTemplate,
            'replacementTemplate',
            'A skipped recurrence occurrence cannot have a replacement '
                'template.',
          );
        }

      case RecurrenceExceptionKind.replacement:
        final changesDate =
            replacementOn != null && replacementOn!.compareTo(scheduledOn) != 0;

        if (!changesDate && replacementTemplate == null) {
          throw ArgumentError.value(
            kind,
            'kind',
            'A replacement recurrence exception must change its date, '
                'transaction template, or both.',
          );
        }
    }
  }

  /// Creates an exception that suppresses one scheduled occurrence.
  factory RecurrenceException.skip({required CalendarDate scheduledOn}) {
    return RecurrenceException(
      scheduledOn: scheduledOn,
      kind: RecurrenceExceptionKind.skip,
    );
  }

  /// Creates an exception replacing one scheduled occurrence.
  ///
  /// At least one of [replacementOn] or [replacementTemplate] must represent
  /// an effective change.
  factory RecurrenceException.replace({
    required CalendarDate scheduledOn,
    CalendarDate? replacementOn,
    TransactionTemplate? replacementTemplate,
  }) {
    return RecurrenceException(
      scheduledOn: scheduledOn,
      kind: RecurrenceExceptionKind.replacement,
      replacementOn: replacementOn,
      replacementTemplate: replacementTemplate,
    );
  }

  /// Whether this exception suppresses its scheduled occurrence.
  bool get isSkipped => kind == RecurrenceExceptionKind.skip;

  /// Whether this exception replaces its scheduled occurrence.
  bool get isReplacement => kind == RecurrenceExceptionKind.replacement;

  /// Effective occurrence date after applying this exception.
  ///
  /// Returns `null` when the occurrence is skipped.
  CalendarDate? get effectiveDate {
    return switch (kind) {
      RecurrenceExceptionKind.skip => null,
      RecurrenceExceptionKind.replacement => replacementOn ?? scheduledOn,
    };
  }

  /// Resolves the transaction template to use for this exception.
  ///
  /// Returns `null` when the occurrence is skipped.
  ///
  /// A replacement without a [replacementTemplate] keeps [seriesTemplate].
  TransactionTemplate? resolveTemplate(TransactionTemplate seriesTemplate) {
    return switch (kind) {
      RecurrenceExceptionKind.skip => null,
      RecurrenceExceptionKind.replacement =>
        replacementTemplate ?? seriesTemplate,
    };
  }
}
