import 'package:axiom/src/core/domain/value_objects/entity_logo.dart';
import 'package:axiom/src/features/assets/domain/value_objects/asset_code.dart';

part 'create_commodity_asset_command.dart';
part 'create_crypto_asset_command.dart';
part 'create_currency_command.dart';
part 'create_stock_asset_command.dart';

/// Base input for creating one persisted asset.
///
/// The command contains only user-supplied creation state. Identity, audit
/// metadata, and entity version are generated by the domain factory.
///
/// Concrete command types deliberately mirror the supported Asset subtypes.
/// This avoids a generic `type` field combined with nullable subtype-specific
/// fields.
sealed class CreateAssetCommand {
  /// Human-readable asset name.
  final String name;

  /// Stable asset code.
  final AssetCode code;

  /// Optional display symbol.
  final String? symbol;

  /// Optional visual logo.
  final EntityLogo? logo;

  /// Number of fractional decimal places supported by the asset.
  final int decimalPlaces;

  /// Creates the common asset creation input.
  const CreateAssetCommand({
    required this.name,
    required this.code,
    this.symbol,
    this.logo,
    required this.decimalPlaces,
  });
}
