import 'package:axiom/src/core/domain/value_objects/calendar_date.dart';
import 'package:axiom/src/core/persistence/mapping/persistence_record.dart';
import 'package:axiom/src/core/persistence/mapping/persistence_record_exception.dart';
import 'package:axiom/src/core/persistence/mapping/persistence_record_helpers.dart';
import 'package:axiom/src/core/persistence/mapping/persistence_record_reader.dart';
import 'package:axiom/src/features/transactions/data/models/transaction_template_persistence_model.dart';
import 'package:axiom/src/features/transactions/domain/enums/recurrence_exception_kind.dart';
import 'package:axiom/src/features/transactions/domain/value_objects/recurrence_exception.dart';

/// Persistence representation of a [RecurrenceException].
///
/// The scheduled date remains the identity of the recurrence slot being
/// overridden. Replacement dates and templates are optional because skip
/// exceptions do not persist replacement values.
final class RecurrenceExceptionPersistenceModel {
  static const String _scheduledOnField = 'scheduledOn';
  static const String _kindField = 'kind';
  static const String _replacementOnField = 'replacementOn';
  static const String _replacementTemplateField = 'replacementTemplate';

  /// Original date generated by the owning recurrence rule.
  final CalendarDate scheduledOn;

  /// Exception behavior applied to the scheduled occurrence.
  final RecurrenceExceptionKind kind;

  /// Replacement occurrence date, when the exception moves the occurrence.
  final CalendarDate? replacementOn;

  /// Replacement transaction template, when the exception changes the
  /// transaction data.
  final TransactionTemplatePersistenceModel? replacementTemplate;

  /// Creates a recurrence-exception persistence model.
  ///
  /// This constructor performs structural assignment only. Exception
  /// invariants are revalidated when [toEntity] reconstructs the domain value.
  const RecurrenceExceptionPersistenceModel({
    required this.scheduledOn,
    required this.kind,
    required this.replacementOn,
    required this.replacementTemplate,
  });

  /// Creates a persistence model from the valid domain [exception].
  factory RecurrenceExceptionPersistenceModel.fromEntity(
    RecurrenceException exception,
  ) {
    return RecurrenceExceptionPersistenceModel(
      scheduledOn: exception.scheduledOn,
      kind: exception.kind,
      replacementOn: exception.replacementOn,
      replacementTemplate: exception.replacementTemplate == null
          ? null
          : TransactionTemplatePersistenceModel.fromEntity(
              exception.replacementTemplate!,
            ),
    );
  }

  /// Reconstructs a persistence model from [record].
  ///
  /// [path] identifies this model's location in the containing persisted
  /// structure and is included in structural error paths.
  ///
  /// Throws [PersistenceRecordException] when a field or nested replacement
  /// template has an invalid persisted shape or value.
  factory RecurrenceExceptionPersistenceModel.fromRecord(
    PersistenceRecord record, {
    required String path,
  }) {
    return withPersistenceRecordPath(path, () {
      final reader = PersistenceRecordReader(record);
      final rawReplacementTemplate = reader.optionalMap(
        _replacementTemplateField,
      );

      return RecurrenceExceptionPersistenceModel(
        scheduledOn: readCalendarDate(
          reader.requiredString(_scheduledOnField),
          field: _scheduledOnField,
        ),
        kind: readPersistenceEnum(
          reader: reader,
          field: _kindField,
          values: RecurrenceExceptionKind.values,
        ),
        replacementOn: readOptionalCalendarDate(reader, _replacementOnField),
        replacementTemplate: rawReplacementTemplate == null
            ? null
            : TransactionTemplatePersistenceModel.fromRecord(
                rawReplacementTemplate,
                path: '$path.$_replacementTemplateField',
              ),
      );
    });
  }

  /// Converts this model to its primitive persistence record representation.
  ///
  /// Optional replacement values remain `null` when they are not configured.
  PersistenceRecord toRecord() {
    return <String, Object?>{
      _scheduledOnField: scheduledOn.toString(),
      _kindField: kind.name,
      _replacementOnField: replacementOn?.toString(),
      _replacementTemplateField: replacementTemplate?.toRecord(),
    };
  }

  /// Reconstructs the domain [RecurrenceException] represented by this model.
  ///
  /// Throws [ArgumentError] when the persisted values violate the exception
  /// invariants.
  RecurrenceException toEntity() {
    return RecurrenceException(
      scheduledOn: scheduledOn,
      kind: kind,
      replacementOn: replacementOn,
      replacementTemplate: replacementTemplate?.toEntity(),
    );
  }
}
