import 'package:axiom/src/core/domain/value_objects/calendar_date.dart';
import 'package:axiom/src/core/persistence/mapping/persistence_record.dart';
import 'package:axiom/src/core/persistence/mapping/persistence_record_exception.dart';
import 'package:axiom/src/core/persistence/mapping/persistence_record_helpers.dart';
import 'package:axiom/src/core/persistence/mapping/persistence_record_reader.dart';
import 'package:axiom/src/features/assets/data/models/asset_amount_persistence_model.dart';
import 'package:axiom/src/features/balance_snapshots/data/models/balance_snapshot_record_key.dart';
import 'package:axiom/src/features/balance_snapshots/domain/value_objects/balance_snapshot.dart';

/// Versioned Sembast persistence representation of one [BalanceSnapshot].
///
/// ## Record identity
///
/// The Sembast record key is generated by [BalanceSnapshotRecordKey] and
/// represents:
///
/// ```text
/// subject type + subject ID + snapshot date
/// ```
///
/// The same values are also stored in the record payload. This intentional
/// redundancy allows persistence integrity checks to detect a record that has
/// been stored under the wrong key.
///
/// ## Versioning
///
/// [recordVersion] describes the persistence representation rather than the
/// domain value object.
///
/// Version `1` contains:
///
/// - typed subject metadata;
/// - snapshot date and numeric date index;
/// - capture timestamp;
/// - asset balances;
/// - denomination amount; and
/// - base valuation amount.
///
/// Future versions can be handled in [fromRecord] without changing the natural
/// Sembast record key.
///
/// ## Historical indexes
///
/// [subjectKeyField] stores a stable subject-only lookup key.
///
/// [snapshotDateEpochDayField] stores the represented calendar date as a
/// numeric UTC epoch-day value.
///
/// A repository can therefore query:
///
/// ```text
/// subjectKey == requested subject
/// snapshotDateEpochDay >= from
/// snapshotDateEpochDay < until
/// ```
///
/// and order numerically by snapshot date.
///
/// [snapshotDateField] remains persisted as a human-readable date and is
/// cross-validated against the numeric index.
///
/// ## Integrity
///
/// Persisted values are untrusted.
///
/// Reconstruction verifies:
///
/// - supported record version;
/// - agreement between record key and payload subject;
/// - agreement between record key and payload date;
/// - agreement between textual date and numeric date index;
/// - valid UTC capture timestamp;
/// - structurally valid nested asset amounts; and
/// - all current [BalanceSnapshot] domain invariants.
final class BalanceSnapshotPersistenceModel {
  /// Current persistence-record schema version.
  static const int currentRecordVersion = 1;

  /// Persistence schema-version field.
  static const String recordVersionField = 'recordVersion';

  /// Subject-type discriminator field.
  static const String subjectTypeField = 'subjectType';

  /// Raw domain subject identity field.
  static const String subjectIdField = 'subjectId';

  /// Stable subject-only query-key field.
  static const String subjectKeyField = 'subjectKey';

  /// Human-readable calendar-date field.
  static const String snapshotDateField = 'snapshotDate';

  /// Numeric calendar-date query field.
  static const String snapshotDateEpochDayField = 'snapshotDateEpochDay';

  /// Capture timestamp field.
  static const String capturedAtField = 'capturedAt';

  /// Per-asset balance collection field.
  static const String assetBalancesField = 'assetBalances';

  /// Subject-denomination total field.
  static const String denominationAmountField = 'denominationAmount';

  /// User-base valuation total field.
  static const String valuationAmountField = 'valuationAmount';

  /// Creates a persistence model from [snapshot].
  factory BalanceSnapshotPersistenceModel.fromEntity(BalanceSnapshot snapshot) {
    final key = BalanceSnapshotRecordKey.fromSubject(
      subject: snapshot.subject,
      snapshotDate: snapshot.snapshotDate,
    );

    return BalanceSnapshotPersistenceModel._(
      recordVersion: currentRecordVersion,
      subjectType: key.subjectType,
      subjectId: key.subjectId,
      subjectKey: key.subjectKey,
      snapshotDate: snapshot.snapshotDate,
      snapshotDateEpochDay: _epochDay(snapshot.snapshotDate),
      capturedAt: snapshot.capturedAt.toUtc(),
      assetBalances: snapshot.assetBalances
          .map(AssetAmountPersistenceModel.fromEntity)
          .toList(growable: false),
      denominationAmount: AssetAmountPersistenceModel.fromEntity(
        snapshot.denominationAmount,
      ),
      valuationAmount: AssetAmountPersistenceModel.fromEntity(
        snapshot.valuationAmount,
      ),
    );
  }

  /// Reconstructs and validates a persistence model from one Sembast record.
  ///
  /// [recordKey] is validated against the redundant subject/date fields stored
  /// in [record].
  ///
  /// Throws [PersistenceRecordException] for malformed, inconsistent, or
  /// unsupported persisted data.
  factory BalanceSnapshotPersistenceModel.fromRecord({
    required String recordKey,
    required PersistenceRecord record,
  }) {
    final reader = PersistenceRecordReader(record);
    final recordVersion = reader.requiredInt(recordVersionField);

    return switch (recordVersion) {
      1 => BalanceSnapshotPersistenceModel._fromVersion1(
        recordKey: recordKey,
        reader: reader,
      ),
      _ => throw PersistenceRecordException(
        field: recordVersionField,
        reason: 'Unsupported balance snapshot record version.',
      ),
    };
  }

  factory BalanceSnapshotPersistenceModel._fromVersion1({
    required String recordKey,
    required PersistenceRecordReader reader,
  }) {
    final key = BalanceSnapshotRecordKey.parse(recordKey);

    final subjectType = reader.requiredString(subjectTypeField);
    final subjectId = reader.requiredString(subjectIdField);
    final subjectKey = reader.requiredString(subjectKeyField);

    final snapshotDate = readCalendarDate(
      reader.requiredString(snapshotDateField),
      field: snapshotDateField,
    );

    final snapshotDateEpochDay = reader.requiredInt(snapshotDateEpochDayField);

    _validateKeyIntegrity(
      key: key,
      subjectType: subjectType,
      subjectId: subjectId,
      subjectKey: subjectKey,
      snapshotDate: snapshotDate,
    );

    final expectedEpochDay = _epochDay(snapshotDate);

    if (snapshotDateEpochDay != expectedEpochDay) {
      throw const PersistenceRecordException(
        field: snapshotDateEpochDayField,
        reason:
            'Persisted snapshot date index does not match the snapshot date.',
      );
    }

    final rawAssetBalances = reader.requiredList(assetBalancesField);

    final assetBalances = <AssetAmountPersistenceModel>[
      for (var index = 0; index < rawAssetBalances.length; index++)
        AssetAmountPersistenceModel.fromRecord(
          persistenceRecordFromListValue(
            rawAssetBalances[index],
            field: '$assetBalancesField[$index]',
          ),
          path: '$assetBalancesField[$index]',
        ),
    ];

    final denominationAmount = AssetAmountPersistenceModel.fromRecord(
      reader.requiredMap(denominationAmountField),
      path: denominationAmountField,
    );

    final valuationAmount = AssetAmountPersistenceModel.fromRecord(
      reader.requiredMap(valuationAmountField),
      path: valuationAmountField,
    );

    return BalanceSnapshotPersistenceModel._(
      recordVersion: currentRecordVersion,
      subjectType: subjectType,
      subjectId: subjectId,
      subjectKey: subjectKey,
      snapshotDate: snapshotDate,
      snapshotDateEpochDay: snapshotDateEpochDay,
      capturedAt: readPersistenceDateTime(reader, capturedAtField),
      assetBalances: assetBalances,
      denominationAmount: denominationAmount,
      valuationAmount: valuationAmount,
    );
  }

  BalanceSnapshotPersistenceModel._({
    required this.recordVersion,
    required this.subjectType,
    required this.subjectId,
    required this.subjectKey,
    required this.snapshotDate,
    required this.snapshotDateEpochDay,
    required this.capturedAt,
    required List<AssetAmountPersistenceModel> assetBalances,
    required this.denominationAmount,
    required this.valuationAmount,
  }) : assetBalances = List.unmodifiable(assetBalances);

  /// Persistence schema version.
  final int recordVersion;

  /// Serialized subject-type discriminator.
  final String subjectType;

  /// Raw subject identity.
  final String subjectId;

  /// Stable subject-only query key.
  final String subjectKey;

  /// Represented calendar date.
  final CalendarDate snapshotDate;

  /// Numeric UTC epoch-day representation of [snapshotDate].
  final int snapshotDateEpochDay;

  /// UTC instant at which this snapshot was calculated.
  final DateTime capturedAt;

  /// Persisted per-asset balances.
  final List<AssetAmountPersistenceModel> assetBalances;

  /// Persisted subject-denomination total.
  final AssetAmountPersistenceModel denominationAmount;

  /// Persisted user-base valuation total.
  final AssetAmountPersistenceModel valuationAmount;

  /// Sembast natural record key.
  String get recordKey {
    return BalanceSnapshotRecordKey.fromParts(
      subjectType: subjectType,
      subjectId: subjectId,
      snapshotDate: snapshotDate,
    ).value;
  }

  /// Reconstructs the immutable domain snapshot.
  ///
  /// Current domain invariants are always revalidated.
  ///
  /// Throws [PersistenceRecordException] when persisted data cannot produce a
  /// valid [BalanceSnapshot].
  BalanceSnapshot toEntity() {
    try {
      final key = BalanceSnapshotRecordKey.fromParts(
        subjectType: subjectType,
        subjectId: subjectId,
        snapshotDate: snapshotDate,
      );

      return BalanceSnapshot(
        subject: key.toSubject(),
        snapshotDate: snapshotDate,
        capturedAt: capturedAt,
        assetBalances: assetBalances
            .map((amount) => amount.toEntity())
            .toList(growable: false),
        denominationAmount: denominationAmount.toEntity(),
        valuationAmount: valuationAmount.toEntity(),
      );
    } on PersistenceRecordException {
      rethrow;
    } on ArgumentError {
      throw const PersistenceRecordException(
        reason:
            'Persisted balance snapshot violates current domain invariants.',
      );
    } // coverage:ignore-start
    on FormatException {
      throw const PersistenceRecordException(
        reason: 'Persisted balance snapshot contains an invalid domain value.',
      );
      // coverage:ignore-end
    }
  }

  /// Serializes this model into primitive Sembast-compatible values.
  PersistenceRecord toRecord() {
    return <String, Object?>{
      recordVersionField: recordVersion,
      subjectTypeField: subjectType,
      subjectIdField: subjectId,
      subjectKeyField: subjectKey,
      snapshotDateField: snapshotDate.toString(),
      snapshotDateEpochDayField: snapshotDateEpochDay,
      capturedAtField: capturedAt.toUtc().toIso8601String(),
      assetBalancesField: assetBalances
          .map((amount) => amount.toRecord())
          .toList(growable: false),
      denominationAmountField: denominationAmount.toRecord(),
      valuationAmountField: valuationAmount.toRecord(),
    };
  }

  static void _validateKeyIntegrity({
    required BalanceSnapshotRecordKey key,
    required String subjectType,
    required String subjectId,
    required String subjectKey,
    required CalendarDate snapshotDate,
  }) {
    if (subjectType != key.subjectType) {
      throw const PersistenceRecordException(
        field: subjectTypeField,
        reason:
            'Persisted snapshot subject type does not match its record key.',
      );
    }

    if (subjectId != key.subjectId) {
      throw const PersistenceRecordException(
        field: subjectIdField,
        reason: 'Persisted snapshot subject ID does not match its record key.',
      );
    }

    if (subjectKey != key.subjectKey) {
      throw const PersistenceRecordException(
        field: subjectKeyField,
        reason:
            'Persisted snapshot subject lookup key does not match its '
            'record key.',
      );
    }

    if (snapshotDate != key.snapshotDate) {
      throw const PersistenceRecordException(
        field: snapshotDateField,
        reason: 'Persisted snapshot date does not match its record key.',
      );
    }
  }

  static int _epochDay(CalendarDate date) {
    return date.toDateTimeUtc().millisecondsSinceEpoch ~/
        Duration.millisecondsPerDay;
  }
}
